Current = "0.3.1"

[[Files]]
  Path = "README.md"
  Prefix = "# memoize v"
  Postfix = ""
  IsNumber = false

[[Files]]
  Path = "package.json"
  Prefix = "\"version\": \""
  Postfix = "\""
  IsNumber = false
